name: run-tests

on:
  push:
  pull_request:

jobs:
  run-tests:

    defaults:
      run:
        shell: bash -l {0}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10', '3.11', '3.12']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: myenv
          environment-file: environment.yml
          auto-activate-base: false
          auto-update-conda: true

      - name: Create conda environment and install dependencies
        run: conda activate myenv

      - name: Install pip
        run: conda install pip

      - name: Install project package from pyproject.toml
        run: |
          pip install .

      - name: Run tests
        run: |
          conda activate myenv
          pytest
